Map: Remove tiny countries in base map
that are single-point or two-point shapes,
since we can't see them anyway.
Will still be shown in the overlay.
Exception: If next country starts with a relative move (m),
leave it in.